// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyeIhuyBI0gKtt5Vi46-ZB9Pzm3RoKf1E',
    appId: '1:704189031986:web:c1f9c06d09889528933e2b',
    messagingSenderId: '704189031986',
    projectId: 'project-flutter-4972e',
    authDomain: 'project-flutter-4972e.firebaseapp.com',
    databaseURL: 'https://project-flutter-4972e-default-rtdb.firebaseio.com',
    storageBucket: 'project-flutter-4972e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd90GwR9tl-VQx_SsRIXRnNRrlqVAiE6A',
    appId: '1:704189031986:android:0de734e0d65077c5933e2b',
    messagingSenderId: '704189031986',
    projectId: 'project-flutter-4972e',
    databaseURL: 'https://project-flutter-4972e-default-rtdb.firebaseio.com',
    storageBucket: 'project-flutter-4972e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2xqJxcDdS8z6dhkKkQw3T6xKdjyTZixE',
    appId: '1:704189031986:ios:42c160b41522b4da933e2b',
    messagingSenderId: '704189031986',
    projectId: 'project-flutter-4972e',
    databaseURL: 'https://project-flutter-4972e-default-rtdb.firebaseio.com',
    storageBucket: 'project-flutter-4972e.appspot.com',
    iosClientId: '704189031986-pthpo39o0rvmb0gv69r0fi1uu8g1saa2.apps.googleusercontent.com',
    iosBundleId: 'com.example.bai4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2xqJxcDdS8z6dhkKkQw3T6xKdjyTZixE',
    appId: '1:704189031986:ios:42c160b41522b4da933e2b',
    messagingSenderId: '704189031986',
    projectId: 'project-flutter-4972e',
    databaseURL: 'https://project-flutter-4972e-default-rtdb.firebaseio.com',
    storageBucket: 'project-flutter-4972e.appspot.com',
    iosClientId: '704189031986-pthpo39o0rvmb0gv69r0fi1uu8g1saa2.apps.googleusercontent.com',
    iosBundleId: 'com.example.bai4',
  );
}
